<?php
$secret = 'oauth:m6xcaw6dx4jo94blvgss4kq3f12if5'; /* Get your Chat OAuth Password here => https://twitchapps.com/tmi/ */

$bot_id = '2x8q1ia3nf9u5shtmd2nzvew033jdw'; // Obtained from https://dev.twitch.tv/console/apps
$bot_secret = 'x46sq2ozwzz080my6y5u5m3dud1qvz'; // Obtained from https://dev.twitch.tv/console/apps


if($token_blob = file_get_contents(getcwd().'/temp/access_token.php')) $bot_token = unserialize($token_blob);
else 
$bot_token = 'pkyx7ehbx3m7eco3vtln9ntzy920xm'; // Obtained from your own server using twitch_oauth.php

if($refresh_blob = file_get_contents(getcwd().'/temp/refresh_token.php')) $refresh_token = unserialize($refresh_blob);
else
$refresh_token = 'h9x6id67dsl55szy5i4oxxqj4qa45clzxnxhync3mrv0lluq8c'; // Obtained from your own server using twitch_oauth.php

$expires_in = '15100'; // Obtained from your own server using twitch_oauth.php (Will be deprecated)

$scope = ["user:edit","user:read:email","viewing_activity_read"];

//DO NOT CHANGE ANYTHING BELOW THIS LINE UNLESS YOU KNOW WHAT YOU'RE DOING!///////////

if($expires_blob = file_get_contents(getcwd().'/temp/expires_time.php')) $expires_in = unserialize($expires_blob);
else $expires_time = time()+60; // Generated by Helix.php
$token_type = "bearer"; //Helix uses Authorization: Bearer instead of AUthorization: Oauth
?>